// A2UI v0.9 prompts, assembled with the Direct JSON prompt generator from
// lib/a2ui/prompt (inlined from the a2ui repo's packages/shadcn; server-safe:
// no React): protocol rules +
// the full shadcn catalog schema contract + OnCall-domain few-shot examples.
// The examples are generated by builders so UI structure changes only need a
// builder edit — the prompt stays in sync automatically.
//
// Surface actions are handled out of band by /api/a2ui_action, which updates
// the originating surface in place.

import {
  A2UI_CLOSE_TAG,
  A2UI_OPEN_TAG,
  applySchemaModifiers,
  generateSystemPrompt,
  removeStrictValidation,
  SHADCN_PROMPT_CATALOG,
} from "@/lib/a2ui/prompt";

export { A2UI_CLOSE_TAG, A2UI_OPEN_TAG };

// The catalog id the client-side A2uiView registers (it renders with the
// shadcn catalog); createSurface messages MUST reference it or the renderer
// throws "Catalog not found".
export const A2UI_CATALOG_ID = SHADCN_PROMPT_CATALOG.catalogSchema
  .catalogId as string;

// Closed-object constraints make the LLM over-constrain harmless extra keys,
// so the schemas handed to the model drop them (Python SDK sample practice).
const PROMPT_CATALOG = applySchemaModifiers(SHADCN_PROMPT_CATALOG, [
  removeStrictValidation,
]);

function buildAlertListExample(): unknown[] {
  const surfaceId = "alerts-overview-1";
  return [
    {
      version: "v0.9",
      createSurface: { surfaceId, catalogId: A2UI_CATALOG_ID },
    },
    {
      version: "v0.9",
      updateComponents: {
        surfaceId,
        components: [
          {
            id: "root",
            component: "Column",
            children: ["alerts-title", "alerts-list"],
          },
          {
            id: "alerts-title",
            component: "Text",
            variant: "h3",
            text: { path: "/title" },
          },
          {
            id: "alerts-list",
            component: "List",
            direction: "vertical",
            children: { componentId: "alert-card", path: "/alerts" },
          },
          { id: "alert-card", component: "Card", child: "alert-body" },
          {
            id: "alert-body",
            component: "Column",
            children: ["alert-head", "alert-desc", "alert-since", "alert-ack"],
          },
          {
            id: "alert-head",
            component: "Row",
            justify: "spaceBetween",
            align: "center",
            children: ["alert-name", "alert-severity"],
          },
          {
            id: "alert-name",
            component: "Text",
            variant: "h4",
            text: { path: "name" },
          },
          {
            id: "alert-severity",
            component: "Badge",
            variant: "destructive",
            text: { path: "severity" },
          },
          {
            id: "alert-desc",
            component: "Text",
            text: { path: "description" },
          },
          {
            id: "alert-since",
            component: "Text",
            variant: "caption",
            text: { path: "startsAt" },
          },
          {
            id: "alert-ack",
            component: "Button",
            variant: "primary",
            child: "alert-ack-label",
            action: {
              event: {
                name: "ack_alert",
                context: {
                  alertname: { path: "name" },
                  severity: { path: "severity" },
                },
              },
            },
          },
          { id: "alert-ack-label", component: "Text", text: "Acknowledge" },
        ],
      },
    },
    {
      version: "v0.9",
      updateDataModel: {
        surfaceId,
        path: "/",
        value: {
          title: "2 firing alerts",
          alerts: [
            {
              name: "HighErrorRate",
              severity: "critical",
              description: "Error rate above 5% on service checkout for 10m.",
              startsAt: "2026-08-17 09:12:00",
            },
            {
              name: "MySQLReplicationLag",
              severity: "warning",
              description: "Replica lag is 45s on db-order-replica-2.",
              startsAt: "2026-08-17 08:40:00",
            },
          ],
        },
      },
    },
  ];
}

function buildMetricsReportExample(): unknown[] {
  const surfaceId = "qps-report-1";
  return [
    {
      version: "v0.9",
      createSurface: { surfaceId, catalogId: A2UI_CATALOG_ID },
    },
    {
      version: "v0.9",
      updateComponents: {
        surfaceId,
        components: [
          {
            id: "root",
            component: "Column",
            children: ["report-title", "qps-chart", "qps-table"],
          },
          {
            id: "report-title",
            component: "Text",
            variant: "h3",
            text: { path: "/title" },
          },
          {
            id: "qps-chart",
            component: "Chart",
            variant: "line",
            data: { path: "/rows" },
            xKey: "time",
            series: [
              { key: "qps", label: "QPS" },
              { key: "errors", label: "Errors" },
            ],
            height: 240,
          },
          {
            id: "qps-table",
            component: "Table",
            caption: "Hourly QPS of service checkout",
            columns: [
              { key: "time", header: "Time" },
              { key: "qps", header: "QPS" },
              { key: "errors", header: "Errors" },
            ],
            rows: { path: "/rows" },
          },
        ],
      },
    },
    {
      version: "v0.9",
      updateDataModel: {
        surfaceId,
        path: "/",
        value: {
          title: "Service checkout QPS (last 3 hours)",
          rows: [
            { time: "10:00", qps: 1240, errors: 3 },
            { time: "11:00", qps: 1685, errors: 12 },
            { time: "12:00", qps: 2210, errors: 5 },
          ],
        },
      },
    },
  ];
}

function buildSilenceFormExample(): unknown[] {
  const surfaceId = "silence-form-1";
  return [
    {
      version: "v0.9",
      createSurface: { surfaceId, catalogId: A2UI_CATALOG_ID },
    },
    {
      version: "v0.9",
      updateComponents: {
        surfaceId,
        components: [
          { id: "root", component: "Card", child: "form-body" },
          {
            id: "form-body",
            component: "Column",
            children: [
              "form-title",
              "alertname-field",
              "hours-field",
              "comment-field",
              "submit-btn",
            ],
          },
          {
            id: "form-title",
            component: "Text",
            variant: "h4",
            text: "Create alert silence",
          },
          {
            id: "alertname-field",
            component: "TextField",
            label: "Alert name",
            value: { path: "/alertname" },
          },
          {
            id: "hours-field",
            component: "TextField",
            label: "Duration (hours)",
            variant: "number",
            value: { path: "/hours" },
          },
          {
            id: "comment-field",
            component: "TextField",
            label: "Comment",
            value: { path: "/comment" },
          },
          {
            id: "submit-btn",
            component: "Button",
            variant: "primary",
            child: "submit-label",
            action: {
              event: {
                name: "create_silence",
                context: {
                  alertname: { path: "/alertname" },
                  hours: { path: "/hours" },
                  comment: { path: "/comment" },
                },
              },
            },
          },
          { id: "submit-label", component: "Text", text: "Create silence" },
        ],
      },
    },
    {
      version: "v0.9",
      updateDataModel: {
        surfaceId,
        path: "/",
        value: { alertname: "HighErrorRate", hours: "2", comment: "" },
      },
    },
  ];
}

// In-place update reply for a create_silence action on the silence form
// surface: upserts the container children with a new status line and writes
// the status value — no createSurface, same surfaceId.
function buildSilenceActionUpdateExample(): unknown[] {
  const surfaceId = "silence-form-1";
  return [
    {
      version: "v0.9",
      updateComponents: {
        surfaceId,
        components: [
          {
            id: "form-body",
            component: "Column",
            children: [
              "form-title",
              "alertname-field",
              "hours-field",
              "comment-field",
              "submit-btn",
              "status-text",
            ],
          },
          {
            id: "status-text",
            component: "Text",
            variant: "caption",
            text: { path: "/status" },
          },
        ],
      },
    },
    {
      version: "v0.9",
      updateDataModel: {
        surfaceId,
        path: "/status",
        value: "Silence created for HighErrorRate (2 hours)",
      },
    },
  ];
}

function renderExample(name: string, messages: unknown[]): string {
  return `---BEGIN ${name}---\n${A2UI_OPEN_TAG}\n${JSON.stringify(messages)}\n${A2UI_CLOSE_TAG}\n---END ${name}---`;
}

// Chat-embedded section: role + protocol workflow rules + full catalog schema
// contract + examples, assembled by the SDK's Direct JSON prompt generator.
export const A2UI_PROMPT_SECTION = generateSystemPrompt(
  "direct-json",
  {
    roleDescription: `## Interactive UI (A2UI v0.9)

Besides markdown you can render interactive UI surfaces with the A2UI v0.9 protocol.`,
    workflowDescription: `- WHEN: only when the answer presents structured data — alert lists, tabular/SQL query results, metric series or trends, or a form the user should fill and confirm. For explanations, how-tos and casual conversation, answer in plain markdown WITHOUT any A2UI block.
- HOW: write a brief markdown summary first (1-3 sentences), then append exactly ONE UI block. The block content is a JSON array of A2UI messages, with no prose inside the tags.
- Message order: createSurface first, then updateComponents, then updateDataModel. Every surface must define a component with id "root".
- createSurface needs a surfaceId that is unique per reply (kebab-case, e.g. "alerts-overview-3") and catalogId "${A2UI_CATALOG_ID}".
- Data binding: {"path":"/x"} reads the surface data model (absolute path). Inside a List item template use relative paths like {"path":"name"}. List template binding: "children":{"componentId":"<template-id>","path":"/items"}.
- Buttons fire actions: "action":{"event":{"name":"<action_name>","context":{...}}} where context values are literals or {"path"} bindings (bindings also work inside list templates and carry current form values).
- Copy real data (tool results, documents) verbatim into updateDataModel — NEVER invent values. If there is no real data, do not render a surface.
- Text and data values render as PLAIN TEXT: never put markdown syntax (**bold**, _italics_, backticked code, [links]) inside component text, table cells or data model values.
- Actions are handled out of band: when the user triggers a component action, a separate request updates that surface in place. Do not describe or simulate action handling in your text replies.`,
    includeSchema: true,
    examples: [
      renderExample("ALERT_LIST_EXAMPLE", buildAlertListExample()),
      renderExample("METRICS_REPORT_EXAMPLE", buildMetricsReportExample()),
      renderExample("FORM_EXAMPLE", buildSilenceFormExample()),
    ].join("\n"),
  },
  PROMPT_CATALOG,
);

// System prompt for the /api/a2ui_action pipeline: the user triggered an
// action on an existing surface and the model must return ONLY the A2UI
// messages that update that same surface in place. The schema contract is
// pruned to update messages, so createSurface/deleteSurface do not even
// validate.
export const A2UI_ACTION_SYSTEM_PROMPT = generateSystemPrompt(
  "direct-json",
  {
    roleDescription: `# Role: A2UI Surface Updater

The user triggered an action on an existing A2UI v0.9 surface. Your job is to return the A2UI messages that update that surface IN PLACE.`,
    workflowDescription: `- Reply with ONLY one A2UI block — no prose outside the tags.
- Use ONLY updateComponents / updateDataModel messages targeting the SAME surfaceId the action came from. NEVER emit createSurface or deleteSurface, and never a different surfaceId.
- updateComponents upserts components by id: include only the components you change or add. To insert a new component, also re-send its parent with the updated children list. Keep all existing component ids and data paths consistent with the current surface.
- Prefer minimal edits: change values with updateDataModel {surfaceId, path, value}; touch updateComponents only when the component tree itself must change.
- Use tools when the action requires real operations or fresh data; copy real results verbatim into the data model — NEVER invent values.
- Always give visible feedback for the action (e.g. a status line or updated values).
- Text and data values render as PLAIN TEXT: no markdown syntax inside component text or data model values.`,
    allowedMessages: ["UpdateComponentsMessage", "UpdateDataModelMessage"],
    includeSchema: true,
    examples: renderExample(
      "SILENCE_ACTION_UPDATE_EXAMPLE",
      buildSilenceActionUpdateExample(),
    ),
  },
  PROMPT_CATALOG,
);

export interface A2uiActionPayload {
  name: string;
  surfaceId: string;
  sourceComponentId?: string;
  context?: Record<string, unknown>;
}

// User prompt for the action pipeline: the action payload plus the full
// current message history of the surface (its authoritative state).
export function buildA2uiActionPrompt(
  action: A2uiActionPayload,
  surfaceMessages: unknown[],
): string {
  return `The user triggered this action:

${JSON.stringify(action)}

Current A2UI messages of surface "${action.surfaceId}" (its full state):

${JSON.stringify(surfaceMessages)}

Return ONLY the A2UI block that updates surface "${action.surfaceId}" in place.`;
}
